#!/usr/bin/env bash
set -euo pipefail

#incredible productivity tool to save me opening firefox

#argument 1 is the mode we are using
mode=$1

#modes:

#uni
if [[ "$mode" == "uni" ]]; then
    xdg-open https://vle.york.ac.uk/ultra/course
    xdg-open https://drive.google.com/drive/u/0/my-drive
    xdg-open https://learnyouahaskell.com/chapters
    xdg-open https://mail.google.com/mail/u/0/#inbox
    exit 0
fi

#coding
if [[ "$mode" == "code" ]]; then
    xdg-open https://learnyouahaskell.com/chapters
    xdg-open https://github.com/lukehcjackson
    #xdg-open https://chatgpt.com/
    exit 0
fi

#obviously never going to use this one
if [[ "$mode" == "procrastinating" ]]; then
    xdg-open https://www.youtube.com/feed/subscriptions
    exit 0
fi

echo "Usage: show mode - either uni, code, or procrastinating"
exit 0